### ISSUE TITLE
11 days left and no release yet?

### ISSUE THREAD

**Issue by wartoz** [ravyn120/Slither.io-Bots#4]

**Comment by ravyn120** [comment]
I'll release it once I finish adding a solution for proxies so you can get a max amount of bots...

**Comment by wartoz** [comment]
nice

**Comment by wartoz** [comment]
any news? :(

**Comment by ravyn120** [comment]
i'm on a vacation atm i'll release it soon :0

**Comment by wartoz** [comment]
"soon" :(
